#!/bin/bash

echo "HTTP/1.1 200 OK"
echo "Date: $(date)"
echo "Connection: close"
echo "Server: my_little_web_server/0.1"
echo "Content-Type: text/html"
echo ""
echo "<html>"
echo "<head>"
echo "<title>facebook page</title>"
echo "</head>"
echo "<body>"
echo "<div>"
echo "	<form action='facebook.html' method='get'>"
echo "		<label>add friend</label>"
echo "		<input name='add_name'/>"
echo "		<button>submit</button>"
echo "	</form>"
echo "<br>"
echo "</div>"
echo "<div>"
echo "  <form action='facebook page.html' method='get'>"
echo "          <label>create account</label>"
echo "          <input name='create_name'/>"
echo "          <button>submit</button>"
echo "	</form>"
echo "<br>"
echo "</div>"
echo "</body>"
echo "</html>"
